# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b611aa1773eb6378c78762d7d2f997b7a1f82cc983fcee2dbcfb0e7b155649c39b01044b56e5b83f7be4951f792944a3a6a69879fd2b8ae5bb36fd67add785e5

test:
  secret_key_base: e6919dda9f240d2419a4fb1021f32ccdec7ea5f63628fcfea470be1415c22c8ec92ebdc5221eafbbb5f9bbe55723d515c76fb2208e51acd5103b3e316ec1cb07

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
